package com.mahanlei.Util;

public enum Message {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    UPDATE_SUCCESS,
    UPDATE_FAILED,
    BUY_SUCCESS,
    BUY_FAILED,
    RELEASE_SUCCESS,
    RELEASE_FAILED,
    EXCHANGE_DISCOUNT_SUCCESS,
    EXCHANGE_DISCOUNT_FAILED,
    USE_DISCOUNT_SUCCESS,
    USE_DISCOUNT_FAILED,

}
